#!/usr/bin/env bash
# nginx intallation and configaration

# Update package index
apt-get update

# Install nginx
apt-get install -y nginx

# Configure nginx to listen on port 80 and serve "Hello World!"
echo '
server {
    listen 80;
    server_name _;

    location / {
        echo "Hello World!";
    }
}
' > /etc/nginx/sites-available/default

# Restart nginx without using systemctl
kill -s HUP $(cat /var/run/nginx.pid)
