#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Update package index and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy via the default configuration
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Define the HAProxy configuration
HAPROXY_CONFIG="
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    maxconn 2000
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend bestamadou.tech
    bind *:80
    default_backend bestamadou.tech_backend

backend bestamadou.tech_backend
    balance roundrobin
    server 528899-web-01 54.144.139.236:80 check
    server 528899-web-02 54.242.186.62:80 check

listen stats
    bind *:8080
    stats enable
    stats uri /stats
    stats refresh 10s
    stats auth admin:password
"

# Replace the HAProxy configuration file with the new configuration
echo "$HAPROXY_CONFIG" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy service
sudo systemctl restart haproxy
