#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend bestamadou.tech
    timeout client  30000
    bind 0:80
    default_backend bestamadou.tech_backend

backend bestamadou.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 528899-web-01 54.144.139.236 check
    server 528899-web-02 54.242.186.62 check
EOT

sudo service haproxy restart
