#!/usr/bin/env bash

# uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

# Define the server address
SERVER_ADDRESS="54.144.139.236"

# Define the path to the private key
PRIVATE_KEY_PATH="~/.ssh/school"

# Use SSH with single-character flags to connect to the server
ssh -i "$PRIVATE_KEY_PATH" ubuntu@"$SERVER_ADDRESS"
